# terminal
cask "ghostty"
# crossh-shell prompt
brew "starship"
# zsh plugins
brew "mcfly"

# browsers
cask "zen"
cask "arc"

# per mouse settings
cask "linearmouse"

# windows like alt-tab
cask "alt-tab"

# preview windows with mouse hover
cask "dockdoor"

# window management
cask "rectangle"

# display system stats in menu bar
cask "stats"

# toolbar management
cask "jordanbaird-ice"

# API tool
cask "bruno"

# database tool
cask "dbeaver-community"

# container management
cask "podman-desktop"

# GPG tools
cask "gpg-suite"

# aldente to help with battery health
cask "aldente"

# Clean uninstall of apps
cask "appcleaner"

# screenshot tool
cask "shottr"

# image compression tool
cask "imageoptim"

# disk visualizer
cask "daisydisk"

# VPN
cask "tailscale-app"

# password manager
cask "bitwarden"

# Ensure to use latest bash version
brew "bash"

# brew ncdu
brew "ncdu"

# zed editor
cask "zed"

# platform tools
# brew "awscli" - no needed for now
brew "age"
brew "argo"
brew "azure-cli"
brew "direnv"
brew "fluxcd/tap/flux"
brew "fzf"
brew "gitleaks"
brew "helm"
brew "k9s"
brew "kubernetes-cli"
brew "kustomize"
brew "libpq" # for psql
brew "nvm"
brew "openjdk"
brew "openshift-cli"
brew "pre-commit"
brew "python"
brew "go"
brew "sops"
brew "tfenv"
brew "tflint"
brew "tofuenv"
brew "uv"
tap "fluxcd/tap"
brew "schemathesis"
# brew "redis"
brew "valkey"
brew "worktrunk"
brew "golangci-lint"
brew "mkdocs"

# firefox
cask "firefox"

# Open Code
tap "anomalyco/tap"
brew "anomalyco/tap/opencode"
cask "opencode-desktop"

# AI tools
brew "llmfit"
cask "ollama-app"

# Cleaning tools
cask "puremac"

# other apps
cask "spotify"
cask "chatgpt"

# A.I tools
cask "claude"
cask "claude-code"
cask "copilot-cli"
